### ISSUE TITLE
action_category

### ISSUE THREAD

**Issue by waymanng** [localytics/ios-samples#2]
Where do you add "action_category=social" when composing the message in the Localytics Dashboard? I've tried putting it into the "Advanced" section, but it doesn't seem to to do anything.

**Comment by Mriegel** [comment]
@waymanng as of now there is no support for passing categories through the dashboard.  It is only available through the Push API.

**Comment by ysamlan** [comment]
@waymanng I'm asking your Localytics account manager (Clint) to reach out to you on this one so we can have a conversation -- this is an area we're looking to add better dashboard support soon.
